server:
  port: 0
spring:
  application:
    name: availability-analysis
  kafka:
    bootstrap-servers: ${KAFKA_URI:http://localhost:9092}

eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      analysis-type: Availability
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
