server:
  port: 0
spring:
  application:
    name: availability-analysis

eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      analysis-type: Availability
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://192.168.1.32:8761/eureka}

